# 04、异常处理
## 1.标准异常
例如：
	BaseException：所有异常的基类
    Exception：常规异常的基类
    StandardError：所有的内建标准异常的基类
    ArithmeticError：所有数值计算异常的基类
	LookupError：无效数据查询的基类
    IndexError：索引超出序列的范围
    KeyError：字典中查找一个不存在的关键字
    MemoryError：内存溢出（可通过删除对象释放内存）
    NameError：尝试访问一个不存在的变量
    TypeError：不同类型间的无效操作
     ValueError：传入无效的参数
     UnicodeError：Unicode相关的异常
      UnicodeDecodeError：Unicode解码时的异常
 注意：异常体系内部有层次关。
## 2.标准警告
例如：
    Warning：警告的基类
    DeprecationWarning：关于被弃用的特征的警告
    FutureWarning：关于构造将来语义会有改变的警告
    UserWarning：用户代码生成的警告
## 3.异常处理语句
### try-except
先执行try子句，若无异常则直接结束执行，否则从发生异常位置跳入except中名字相符的子句中执行，执行结束后跳回原来位置继续执行try子句。注意，若异常在except中无匹配名字则异常会传递回上层try中。
```python
try:
    f = open('test.txt')
    print(f.read())
    f.close()
except OSError:
    print('打开文件出错')
```
此外，except可能有多个，代表了不同的异常，进行不同的处理。
常会传递回上层try中。
```python
try:
    int("猪鼻子")
    s = 1 + '1'
    f = open('test.txt')
    print(f.read())
    f.close()
except OSError as error:
    print('打开文件出错\n原因是：' + str(error))
except TypeError as error:
    print('类型出错\n原因是：' + str(error))
except ValueError as error:
    print('数值出错\n原因是：' + str(error))
```
### try-except-finally
finally为try-except执行之后再执行的部分，如果异常没有被except处理，则会在finally中出现，即从try传递到finnally。
```python
def divide(x, y):
    try:
        result = x / y
        print("result is", result)
    except ZeroDivisionError:
        print("division by zero!")
    finally:
        print("executing finally clause")


divide(2, 1)
divide(2, 0)
divide("2", "1")
# TypeError: unsupported operand type(s) for /: 'str' and 'str'
```
### try-except-else
else中的部分是在try中无异常后才会执行。
```python
try:
    fh = open("testfile", "w")
    fh.write("这是一个测试文件，用于测试异常!!")
except IOError:
    print("Error: 没有找到文件或读取文件失败")
else:
    print("内容写入文件成功")
    fh.close()
```
### raise
等同于直接引起一个异常。
```python
try:
    raise NameError('HiThere')
except NameError:
    print('An exception flew by!')
    # An exception flew by!
```
## 4.猜数字
题目描述:电脑产生一个零到100之间的随机数字，然后让用户来猜，如果用户猜的数字比这个数字大，提示太大，否则提示太小，当用户正好猜中电脑会提示，"恭喜你猜到了这个数是......"。在用户每次猜测之前程序会输出用户是第几次猜测，如果用户输入的根本不是一个数字，程序会告诉用户"输入无效"。
```python
import random
SecretNumber = random.randint(0,101)

def NumJudgment(GuessNumber):
    try:
        return int(GuessNumber)
    except ValueError:
        print("输入无效!")  
        return False

Count = 1
Guess = 0
print("猜一个0-100的数字吧！")
while Guess != SecretNumber:
    print("这是你第" + str(Count) + "次尝试了！")
    Guess = NumJudgment(input())
    if Guess != False:
        if Guess < SecretNumber:
            print("太小！")
        elif Guess > SecretNumber:
            print("太大！")
        else:
            print("恭喜你猜对了！")
            break
    Count = Count + 1
```